# Generated by Django 5.2.5 on 2025-08-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobposting_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='isCancel',
            new_name='is_cancel',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='cityCode',
            new_name='city_code',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
