# Generated by Django 5.2.5 on 2025-08-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_jobposting_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job',
            new_name='job_posting',
        ),
    ]
