# Generated by Django 5.2.5 on 2025-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_iscancel_application_is_cancel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Ứng viên'), ('EMPLOYER', 'Nhà tuyển dụng')], default='CANDIDATE', max_length=20),
        ),
    ]
