# Generated by Django 5.2.5 on 2025-08-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_job_application_job_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='owner',
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.cv'),
            preserve_default=False,
        ),
    ]
