# Generated by Django 5.2.5 on 2025-08-30 07:58

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_application_owner_application_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(upload_to='cvs/', validators=[app.models.validate_pdf]),
        ),
    ]
