# Generated by Django 5.2.5 on 2025-08-31 07:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
