# Generated by Django 5.2.5 on 2025-09-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(default='Công ty ABC', max_length=100),
            preserve_default=False,
        ),
    ]
