# Generated by Django 5.2.5 on 2025-09-03 15:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobposting_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, storage=app.models.get_dynamic_storage, upload_to='avatars/'),
        ),
    ]
