# Generated by Django 5.2.5 on 2025-09-03 15:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='image',
            field=models.ImageField(null=True, storage=app.models.get_dynamic_storage, upload_to='job-postings/'),
        ),
    ]
