# Generated by Django 5.2.5 on 2025-09-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('SKILL', 'Kỹ năng'), ('FIELD', 'Lĩnh vực'), ('JOB_TYPE', 'Hình thức làm việc'), ('LEVEL', 'Cấp bậc'), ('LANGUAGE', 'Ngôn ngữ'), ('BENEFIT', 'Phúc lợi')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='app.tag'),
        ),
    ]
