# Generated by Django 5.2.5 on 2025-09-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tag_jobposting_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='district_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='ward_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
