# Generated by Django 5.2.5 on 2025-09-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_jobposting_district_code_jobposting_ward_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
